### ISSUE TITLE
Gateway timeout error

### ISSUE THREAD

**Issue by davosian** [jsiebens/hashi-up#31] opened 2022-01-13 07:34 UTC
I have set up a cluster with nomad, consul and vault using hashi-up, but I receive gateway timeout errors when I connect to one nomad client ip but request a service running on a second nomad client (e.g. when trying one of nomad's load balancing tutorials). Since I am not sure whether this has to do with hashi-up, I asked for help on the nomad forum: https://discuss.hashicorp.com/t/internal-routing-problem/34201

This is how I deployed my stack: https://github.com/davosian/home-cluster-v2#nomad-consul-and-vault-installation
Am I missing something?

**Comment by jsiebens** [comment] 2022-01-24 06:13
hi @davosian 

I see you've got some answers on the nomad forum. I think the issue is not really related to hashi-up but more on how to configure nomad which can highly depend on your environment.

Closing this issue now.

Thanks for using hashi-up! :-)

**Closed by jsiebens** 2022-01-24 06:13 UTC

**Comment by davosian** [comment] 2022-01-24 08:48
Perfectly fine, thank you @jsiebens.

Btw., using hashi-up is a pleasure to use: works great and the documentation is well written.
